baseurl: "" # OPTIONAL: the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Additional build settings go here
permalink: simple

timezone: America/Los_Angeles

# components_dir:
#   - ../shared/components
#   - _components

collections:
  docs:
    output: true
    permalink: /:collection/:path
    sort_by: order
    name: Documentation

defaults:
  - scope:
      path: _docs
    values:
      layout: docs
  - scope:
      path: _posts
    values:
      layout: post
      category: news
  - scope:
      path: _posts/drafts
    values:
      published: false

pagination:
  enabled: true
